// <auto-generated />
using System;
using ByteBill_BS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ByteBill_BS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218144222_AddJobOrderPriorityAndEstCompletion")]
    partial class AddJobOrderPriorityAndEstCompletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ByteBill_BS.Models.AccountingEntry", b =>
                {
                    b.Property<long>("AccountingEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AccountingEntryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountingEntryId"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Credit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Debit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Memo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.Property<long?>("SourceInvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("SourceInvoiceID");

                    b.Property<long?>("SourcePaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("SourcePaymentID");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AccountingEntryId");

                    b.HasIndex("ShopId");

                    b.HasIndex("SourceInvoiceId");

                    b.HasIndex("SourcePaymentId");

                    b.ToTable("ACCOUNTING_ENTRY", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AuditLogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("AuditLogId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.CreditDebitAdjustment", b =>
                {
                    b.Property<long>("AdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AdjustmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdjustmentId"));

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedByUserID");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("InvoiceID");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AdjustmentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("CREDIT_DEBIT_ADJUSTMENT", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.HasKey("CustomerId");

                    b.HasIndex("ShopId");

                    b.ToTable("CUSTOMERS", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.Device", b =>
                {
                    b.Property<long>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DeviceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeviceId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerID");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("DeviceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("DEVICES", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.InventoryItem", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("QtyOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("ItemId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShopId", "SKU")
                        .IsUnique();

                    b.ToTable("INVENTORY_ITEMS", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.InventoryTxn", b =>
                {
                    b.Property<long>("InventoryTxnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("InventoryTxnID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InventoryTxnId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ReferenceID");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TxnType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("InventoryTxnId");

                    b.HasIndex("ItemId");

                    b.ToTable("INVENTORY_TXN", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.Invoice", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("InvoiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceId"));

                    b.Property<decimal>("AmountPaid")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerID");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("InvoiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("JobOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("JobOrderID");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unpaid");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalAdjustments")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobOrderId")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.HasIndex("ShopId", "InvoiceNo")
                        .IsUnique();

                    b.ToTable("INVOICES", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.InvoiceLine", b =>
                {
                    b.Property<long>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("InvoiceLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceLineId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("InvoiceID");

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Qty] * [UnitPrice]", true);

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("INVOICE_LINES", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.JobOrder", b =>
                {
                    b.Property<long>("JobOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("JobOrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobOrderId"));

                    b.Property<long?>("AssignedTechUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("AssignedTechUserID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedByUserID");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerID");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("DeviceID");

                    b.Property<string>("DiagnosisNotes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EstimatedCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobOrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemReported")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Created");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("JobOrderId");

                    b.HasIndex("AssignedTechUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShopId", "JobOrderNo")
                        .IsUnique();

                    b.ToTable("JOB_ORDERS", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.JobOrderPart", b =>
                {
                    b.Property<long>("JobOrderPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("JobOrderPartID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobOrderPartId"));

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.Property<long>("JobOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("JobOrderID");

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[QtyUsed] * [UnitPrice]", true);

                    b.Property<int>("QtyUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("JobOrderPartId");

                    b.HasIndex("ItemId");

                    b.HasIndex("JobOrderId");

                    b.ToTable("JOB_ORDER_PARTS", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.JobOrderService", b =>
                {
                    b.Property<long>("JobOrderServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("JobOrderServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobOrderServiceId"));

                    b.Property<long>("JobOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("JobOrderID");

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Qty] * [UnitPrice]", true);

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ServiceID");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("JobOrderServiceId");

                    b.HasIndex("JobOrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("JOB_ORDER_SERVICES", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.JobOrderStatusHistory", b =>
                {
                    b.Property<long>("JobOrderStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("JobOrderStatusHistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobOrderStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("ChangedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ChangedByUserID");

                    b.Property<long>("JobOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("JobOrderID");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("JobOrderStatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("JobOrderId");

                    b.ToTable("JOB_ORDER_STATUS_HISTORY", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.PayMongoTxn", b =>
                {
                    b.Property<long>("PayMongoTxnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PayMongoTxnID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PayMongoTxnId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("PayMongoPaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("PayMongoPaymentIntentID");

                    b.Property<string>("PayMongoStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("PaymentID");

                    b.Property<string>("RawResponse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PayMongoTxnId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("PAYMONGO_TXN", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("PaymentNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("ReceivedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ReceivedByUserID");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Confirmed");

                    b.HasKey("PaymentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("ShopId");

                    b.ToTable("PAYMENTS", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.PaymentAllocation", b =>
                {
                    b.Property<long>("PaymentAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PaymentAllocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentAllocationId"));

                    b.Property<decimal>("AmountApplied")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("InvoiceID");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("PaymentID");

                    b.HasKey("PaymentAllocationId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PaymentId", "InvoiceId")
                        .IsUnique();

                    b.ToTable("PAYMENT_ALLOCATION", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.ServiceCatalog", b =>
                {
                    b.Property<long>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ServiceId"));

                    b.Property<decimal>("BasePrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("ServiceCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("ServiceCategoryID");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.HasKey("ServiceId");

                    b.HasIndex("ServiceCategoryId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShopId", "ServiceName")
                        .IsUnique();

                    b.ToTable("SERVICE_CATALOG", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.ServiceCategory", b =>
                {
                    b.Property<long>("ServiceCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ServiceCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ServiceCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.HasKey("ServiceCategoryId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShopId", "CategoryName")
                        .IsUnique();

                    b.ToTable("SERVICE_CATEGORY", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.Shop", b =>
                {
                    b.Property<long>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShopId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ShopCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("ShopId");

                    b.HasIndex("ShopCode")
                        .IsUnique();

                    b.ToTable("SHOP", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("InAppNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("light");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShopId", "UserName")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.UserRoleAssignment", b =>
                {
                    b.Property<long>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserRoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserRoleId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleID");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("USER_ROLES", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.XeroSyncLog", b =>
                {
                    b.Property<long>("XeroSyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("XeroSyncLogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("XeroSyncLogId"));

                    b.Property<long?>("AccountingEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("AccountingEntryID");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("InvoiceID");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("PaymentID");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long?>("SyncedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SyncedByUserID");

                    b.Property<string>("XeroRecordId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("XeroRecordID");

                    b.HasKey("XeroSyncLogId");

                    b.HasIndex("AccountingEntryId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ShopId");

                    b.HasIndex("SyncedByUserId");

                    b.ToTable("XERO_SYNC_LOG", (string)null);
                });

            modelBuilder.Entity("ByteBill_BS.Models.AccountingEntry", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.Invoice", "SourceInvoice")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("SourceInvoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ByteBill_BS.Models.Payment", "SourcePayment")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("SourcePaymentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Shop");

                    b.Navigation("SourceInvoice");

                    b.Navigation("SourcePayment");
                });

            modelBuilder.Entity("ByteBill_BS.Models.AuditLog", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ByteBill_BS.Models.CreditDebitAdjustment", b =>
                {
                    b.HasOne("ByteBill_BS.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.Invoice", "Invoice")
                        .WithMany("Adjustments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Customer", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("Customers")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Device", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Customer", "Customer")
                        .WithMany("Devices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ByteBill_BS.Models.InventoryItem", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ByteBill_BS.Models.InventoryTxn", b =>
                {
                    b.HasOne("ByteBill_BS.Models.InventoryItem", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Invoice", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.JobOrder", "JobOrder")
                        .WithOne("Invoice")
                        .HasForeignKey("ByteBill_BS.Models.Invoice", "JobOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("Invoices")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("JobOrder");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ByteBill_BS.Models.InvoiceLine", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Invoice", "Invoice")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ByteBill_BS.Models.JobOrder", b =>
                {
                    b.HasOne("ByteBill_BS.Models.User", "AssignedTechUser")
                        .WithMany()
                        .HasForeignKey("AssignedTechUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ByteBill_BS.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.Customer", "Customer")
                        .WithMany("JobOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.Device", "Device")
                        .WithMany("JobOrders")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("JobOrders")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedTechUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Device");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ByteBill_BS.Models.JobOrderPart", b =>
                {
                    b.HasOne("ByteBill_BS.Models.InventoryItem", "Item")
                        .WithMany("JobOrderParts")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.JobOrder", "JobOrder")
                        .WithMany("JobOrderParts")
                        .HasForeignKey("JobOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("JobOrder");
                });

            modelBuilder.Entity("ByteBill_BS.Models.JobOrderService", b =>
                {
                    b.HasOne("ByteBill_BS.Models.JobOrder", "JobOrder")
                        .WithMany("JobOrderServices")
                        .HasForeignKey("JobOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.ServiceCatalog", "Service")
                        .WithMany("JobOrderServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobOrder");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ByteBill_BS.Models.JobOrderStatusHistory", b =>
                {
                    b.HasOne("ByteBill_BS.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.JobOrder", "JobOrder")
                        .WithMany("StatusHistory")
                        .HasForeignKey("JobOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("JobOrder");
                });

            modelBuilder.Entity("ByteBill_BS.Models.PayMongoTxn", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Payment", "Payment")
                        .WithOne("PayMongoTxn")
                        .HasForeignKey("ByteBill_BS.Models.PayMongoTxn", "PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Payment", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("Payments")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ByteBill_BS.Models.PaymentAllocation", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Invoice", "Invoice")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.Payment", "Payment")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ByteBill_BS.Models.ServiceCatalog", b =>
                {
                    b.HasOne("ByteBill_BS.Models.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("ServiceCatalogs")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceCategory");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ByteBill_BS.Models.ServiceCategory", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("ServiceCategories")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ByteBill_BS.Models.User", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("Users")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ByteBill_BS.Models.UserRoleAssignment", b =>
                {
                    b.HasOne("ByteBill_BS.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ByteBill_BS.Models.XeroSyncLog", b =>
                {
                    b.HasOne("ByteBill_BS.Models.AccountingEntry", "AccountingEntry")
                        .WithMany("XeroSyncLogs")
                        .HasForeignKey("AccountingEntryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ByteBill_BS.Models.Invoice", "Invoice")
                        .WithMany("XeroSyncLogs")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ByteBill_BS.Models.Payment", "Payment")
                        .WithMany("XeroSyncLogs")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ByteBill_BS.Models.Shop", "Shop")
                        .WithMany("XeroSyncLogs")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ByteBill_BS.Models.User", "SyncedByUser")
                        .WithMany()
                        .HasForeignKey("SyncedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AccountingEntry");

                    b.Navigation("Invoice");

                    b.Navigation("Payment");

                    b.Navigation("Shop");

                    b.Navigation("SyncedByUser");
                });

            modelBuilder.Entity("ByteBill_BS.Models.AccountingEntry", b =>
                {
                    b.Navigation("XeroSyncLogs");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Customer", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Invoices");

                    b.Navigation("JobOrders");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Device", b =>
                {
                    b.Navigation("JobOrders");
                });

            modelBuilder.Entity("ByteBill_BS.Models.InventoryItem", b =>
                {
                    b.Navigation("JobOrderParts");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Invoice", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("Adjustments");

                    b.Navigation("InvoiceLines");

                    b.Navigation("PaymentAllocations");

                    b.Navigation("XeroSyncLogs");
                });

            modelBuilder.Entity("ByteBill_BS.Models.JobOrder", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("JobOrderParts");

                    b.Navigation("JobOrderServices");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Payment", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("PayMongoTxn");

                    b.Navigation("PaymentAllocations");

                    b.Navigation("XeroSyncLogs");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ByteBill_BS.Models.ServiceCatalog", b =>
                {
                    b.Navigation("JobOrderServices");
                });

            modelBuilder.Entity("ByteBill_BS.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("ByteBill_BS.Models.Shop", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("AuditLogs");

                    b.Navigation("Customers");

                    b.Navigation("InventoryItems");

                    b.Navigation("Invoices");

                    b.Navigation("JobOrders");

                    b.Navigation("Payments");

                    b.Navigation("ServiceCatalogs");

                    b.Navigation("ServiceCategories");

                    b.Navigation("Users");

                    b.Navigation("XeroSyncLogs");
                });

            modelBuilder.Entity("ByteBill_BS.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
