-- Idempotent schema patch for phone encryption + hash support

-- USERS
IF COL_LENGTH('USERS', 'PhoneHash') IS NULL
    ALTER TABLE USERS ADD PhoneHash NVARCHAR(64) NULL;

IF COL_LENGTH('USERS', 'Phone') IS NOT NULL
    ALTER TABLE USERS ALTER COLUMN Phone NVARCHAR(512) NULL;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes WHERE name = 'IX_USERS_PhoneHash' AND object_id = OBJECT_ID('USERS')
)
    CREATE INDEX IX_USERS_PhoneHash ON USERS(PhoneHash);

-- CUSTOMERS
IF COL_LENGTH('CUSTOMERS', 'PhoneHash') IS NULL
    ALTER TABLE CUSTOMERS ADD PhoneHash NVARCHAR(64) NULL;

IF COL_LENGTH('CUSTOMERS', 'Phone') IS NOT NULL
    ALTER TABLE CUSTOMERS ALTER COLUMN Phone NVARCHAR(512) NULL;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes WHERE name = 'IX_CUSTOMERS_PhoneHash' AND object_id = OBJECT_ID('CUSTOMERS')
)
    CREATE INDEX IX_CUSTOMERS_PhoneHash ON CUSTOMERS(PhoneHash);

-- SHOP
IF COL_LENGTH('SHOP', 'PhoneHash') IS NULL
    ALTER TABLE SHOP ADD PhoneHash NVARCHAR(64) NULL;

IF COL_LENGTH('SHOP', 'Phone') IS NOT NULL
    ALTER TABLE SHOP ALTER COLUMN Phone NVARCHAR(512) NULL;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes WHERE name = 'IX_SHOP_PhoneHash' AND object_id = OBJECT_ID('SHOP')
)
    CREATE INDEX IX_SHOP_PhoneHash ON SHOP(PhoneHash);
